[zta_baseline_summary]
homePath = $SPLUNK_DB/zta_baseline_summary/db
coldPath = $SPLUNK_DB/zta_baseline_summary/colddb
thawedPath = $SPLUNK_DB/zta_baseline_summary/thaweddb
maxTotalDataSizeMB = 10240
