[zta_baseline_summary]
homePath = $SPLUNK_DB/zta_baseline_summary/db
coldPath = $SPLUNK_DB/zta_baseline_summary/colddb
thawedPath = $SPLUNK_DB/zta_baseline_summary/thaweddb
maxTotalDataSizeMB = 10240

[zta_envoy]
homePath = $SPLUNK_DB/zta_envoy/db
coldPath = $SPLUNK_DB/zta_envoy/colddb
thawedPath = $SPLUNK_DB/zta_envoy/thaweddb
maxTotalDataSizeMB = 10240

[zta_snort]
homePath = $SPLUNK_DB/zta_snort/db
coldPath = $SPLUNK_DB/zta_snort/colddb
thawedPath = $SPLUNK_DB/zta_snort/thaweddb
maxTotalDataSizeMB = 10240

[zta_nftables]
homePath = $SPLUNK_DB/zta_nftables/db
coldPath = $SPLUNK_DB/zta_nftables/colddb
thawedPath = $SPLUNK_DB/zta_nftables/thaweddb
maxTotalDataSizeMB = 10240

[zta_mongodb]
homePath = $SPLUNK_DB/zta_mongodb/db
coldPath = $SPLUNK_DB/zta_mongodb/colddb
thawedPath = $SPLUNK_DB/zta_mongodb/thaweddb
maxTotalDataSizeMB = 10240

[zta_mongodb_audit]
homePath = $SPLUNK_DB/zta_mongodb_audit/db
coldPath = $SPLUNK_DB/zta_mongodb_audit/colddb
thawedPath = $SPLUNK_DB/zta_mongodb_audit/thaweddb
maxTotalDataSizeMB = 10240
