[envoy:access]
FIELDALIAS-zta_network_envoy = source_address AS src_ip
FIELDALIAS-zta_user_envoy = x_user AS user

[opa:decision]
FIELDALIAS-zta_network_opa = source_address AS src_ip

[snort:alert_json]
FIELDALIAS-zta_network_snort = src_addr AS src_ip

[mongodb:audit]
FIELDALIAS-zta_network_mongo = ip AS src_ip
FIELDALIAS-zta_user_mongo = param.user AS user

